### ISSUE TITLE
Different node color for light theme

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#121]
![image](https://github.com/user-attachments/assets/566347a0-82fc-4fd4-9cf8-3d66e740fba3)
![image](https://github.com/user-attachments/assets/7c0b4422-dd43-4818-a59d-abc97ea16c84)

**Comment by without-ordinary** [comment]
This request is my fault since I might be the first user to need the light theme for accessibility and the ultra-dark theme was actually a blocker for me getting in to using Comfy seriously last year. So turbo thanks for looking in to this issue. :>

From my digging to fix this for myself, the preset color pallet in LightNode is statically configured. Ideally themes should be able to define the pallet colors.

This wouldn't be too big of an issue, but: some default and custom nodes force themselves to pallet colors (some pick a fixed color, others randomize each time...), while some will save being recolored back to default, many will change on load and do not save being set to default in the workflow; when loading other's workflows, I have to select all and recolor to be able to read the text; and some extensions make use of pallet colors for their functionality, eg. toggle bypass on all groups set to color X.

As a short-term workaround, I've started working on a mid-tone dark theme (similar to Discord's default, as my visual issues aren't an affected as much there). So far the one issue this theme is having is group titles are very hard to see, but it is the same limitation with the fixed pallet colors.
![image](https://github.com/user-attachments/assets/170ea847-5966-45f6-9b64-46c55bfe3d92)

**Comment by huchenlei** [comment]
> This request is my fault since I might be the first user to need the light theme for accessibility and the ultra-dark theme was actually a blocker for me getting in to using Comfy seriously last year. So turbo thanks for looking in to this issue. :>
> 
> From my digging to fix this for myself, the preset color pallet in LightNode is statically configured. Ideally themes should be able to define the pallet colors.
> 
> This wouldn't be too big of an issue, but: some default and custom nodes force themselves to pallet colors (some pick a fixed color, others randomize each time...), while some will save being recolored back to default, many will change on load and do not save being set to default in the workflow; when loading other's workflows, I have to select all and recolor to be able to read the text; and some extensions make use of pallet colors for their functionality, eg. toggle bypass on all groups set to color X.
> 
> As a short-term workaround, I've started working on a mid-tone dark theme (similar to Discord's default, as my visual issues aren't an affected as much there). So far the one issue this theme is having is group titles are very hard to see, but it is the same limitation with the fixed pallet colors. ![image](https://private-user-images.githubusercontent.com/20104884/348405050-170ea847-5966-45f6-9b64-46c55bfe3d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzExODQsIm5iZiI6MTcyMDgzMDg4NCwicGF0aCI6Ii8yMDEwNDg4NC8zNDg0MDUwNTAtMTcwZWE4NDctNTk2Ni00NWY2LTliNjQtNDZjNTViZmUzZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAwMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzQ4NmIyZjJkODc4M2QwN2VhZmMxNGMwNzk5NjVkZDZmNTQxYjY2MTlhM2ViNTk0ZjFjZWJhNDRiMzY2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JxKodgf5j2IZkwCDnX4Yp73-CUwemF6iVTidtxO65qE)

We can shift the color's brightness when light mode is applied. WDYT?

**Comment by huchenlei** [comment]
![image](https://github.com/user-attachments/assets/000eb519-67a9-43c6-aaf4-f70ca2154585)
![image](https://github.com/user-attachments/assets/206a7f35-a870-4aab-88b0-3592279c3ed2)
