### ISSUE TITLE
[bug] "Dynamic" widgets deserialization issue

### ISSUE THREAD

**Issue by melMass** [Comfy-Org/ComfyUI_frontend#155]
Nodes that have "dynamic" widgets: widgets that show/hide based on the value of others, seem to trip up the deserialazation.

A good example to test is the `Load Video (Upload)` from [vhs](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) by @AustinMroz

|before reload| after reload|
|-|-|
|<img src="https://github.com/user-attachments/assets/bb38cf6d-8da3-4bae-b400-f2b0f96dee15"/>| <img src="https://github.com/user-attachments/assets/f1ee16be-9e7a-488c-bf9f-78a27260e57d"/>

**Comment by huchenlei** [comment]
Can you explain more on what is the expected behavior, and whether that issue is specific to the TS repo vs the legacy frontend in main ComfyUI repo?

**Comment by AustinMroz** [comment]
I've started looking into it as well and can expound a bit.

VHS nodes utilize onSerialize and onConfigure to instead store state as an object mapping widget names to widget values. This was done specifically to allow nodes to correctly migrate when a new input is added in the middle of other inputs, but most functionality added since then, particularly the dynamically managed widgets of Video Combine have only ever been tested under this modified mapping.

Serialization happens properly,  but on deserialization, to my limited understanding of the new code, it appears that zod is happily converting  the object mapping created by VHS into a Array as is the standardized format.

Frankly I'm conflicted on what path to suggest moving forward. While I'm quite happy with the system in use by VHS, I won't deny that it breaks convention.

**Comment by melMass** [comment]
It is (to my knowledge) only happening in the new UI.
Basically to reproduce:
- Open a blank workflow
- Create one node that have those dynamic widgets
- Reload, the values get shuffled on the widgets

Edit: Ah austin just answered much better :)

**Comment by melMass** [comment]
> While I'm quite happy with the system in use by VHS, I won't deny that it breaks convention.

Maybe it's a good opportunity to think of a proper "builtin" way to have conditional widgets like that, I would use it

**Comment by huchenlei** [comment]
> I've started looking into it as well and can expound a bit.
> 
> VHS nodes utilize onSerialize and onConfigure to instead store state as an object mapping widget names to widget values. This was done specifically to allow nodes to correctly migrate when a new input is added in the middle of other inputs, but most functionality added since then, particularly the dynamically managed widgets of Video Combine have only ever been tested under this modified mapping.
> 
> Serialization happens properly, but on deserialization, to my limited understanding of the new code, it appears that zod is happily converting the object mapping created by VHS into a Array as is the standardized format.
> 
> Frankly I'm conflicted on what path to suggest moving forward. While I'm quite happy with the system in use by VHS, I won't deny that it breaks convention.

Thanks for the insight! I think the issue came from https://github.com/Comfy-Org/ComfyUI_frontend/pull/149. I definitely need to dig into a bit more to see how things are handled.
