### ISSUE TITLE
[Feature Request]: Better Errorhandling

### ISSUE THREAD

**Issue by gisu** [Comfy-Org/ComfyUI_frontend#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have now spent almost 3 hours in my workflow to find out which nodes are the reason why the new frontend shows errors when starting with schema, but then does not load the workflow.  In the end it was the context nodes from RGThree.

The real problem is that the workflow works without any problems. And anyone who sets up a workflow with the new frontend will have no problems. Only when he launches his workflow or performs a reload in the browser will he find an empty workflow with ZOD schema errors.

As nice as the idea of realtime timechecking is, it becomes a problem here, because debugging the workflows is not really simplified if the error message only shows node numbers (those who hide nodes with info fields to clean up have an even harder time).

It would be ideal if you get a warning when dropping the node that it is working against the ZOD scheme. Alternatively, affected nodes are marked when loading / reloading the workflow and the workflow remains visible. Last option a log file with the names, IDs etc. of the affected nodes.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by huchenlei** [comment]
There are 2 types of zod schema checks, 1. workflow validation 2. node def validation. Currently the if a node def is invalid, it get dropped with a warning message in the console already. 

![image](https://github.com/user-attachments/assets/3f6c1500-fc8c-44ca-bd34-f54303107e5c)

**Comment by huchenlei** [comment]
Can you share your browser log when you load the workflow?

**Comment by gisu** [comment]
So if I start with a blank workflow and, for example, drop the context big node (rgthree) into the workflow, I get a warning message from RGThree.js

![image](https://github.com/user-attachments/assets/11d329e9-470b-4b97-b120-d8bbc4a68935)

After the reload

![image](https://github.com/user-attachments/assets/cff505ec-5ee1-441b-b1e5-facfc32ec943)

Automatic CFG is not included in the workflow, and the AV_IPAdapter comes from the Art_Venture plugin, which is also not included in the workflow. I have uninstalled both. Empty workflow, context big dropped into the workflow, reload.

![image](https://github.com/user-attachments/assets/c4f4e7f3-bc23-47a5-b093-7526eaab8d06)
![image](https://github.com/user-attachments/assets/30cb433c-f400-453f-b025-b8cc9b4f0b8d)
There are again three inputs in the Context Big module, but you can only see the error in the Alert Box after the reload.

**Comment by huchenlei** [comment]
This is a workflow validation error. It probably has nothing to do with node def. There might be a possibility that some custom nodes is trying to extending the workflow by overwriting the node inputs type as array instead of string. We strongly discourage this behavior done by custom nodes on hijacking existing fields in workflow JSON.

Can you share the workflow that causes this error? Can you also share a list of extensions active when this workflow is saved?

**Comment by huchenlei** [comment]
BTW, the RGThree warning is reminding you to update efficiency_nodes_comfyui custom node. This is not caused by the new frontend.

![image](https://github.com/user-attachments/assets/a5529f8b-baaf-4026-8298-3bdefc5320f6)

**Comment by gisu** [comment]
I don't have any more error messages in the browser. I have uploaded a small workflow for you, which only has the Context Big Node in it and you can already see the behaviour there (my current workflow is much larger but uses the Context Big Nodes).

[testflow.json](https://github.com/user-attachments/files/16568524/testflow.json)

I have this behaviour on both Windows and Mac. The ComfyUi version on Mac also has fewer custom nodes installed (I only use it to write nodes)

```   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI_Dragos_Nodes
   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/FreeU_Advanced
   0.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyLiterals
   0.1 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfUI-Foxpack
   0.2 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/comfyui-art-venture
   0.4 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI-Crystools
   1.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   2.0 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   3.2 seconds: /Applications/Data/Packages/ComfyUI/custom_nodes/was-node-suite-comfyui```

**Comment by huchenlei** [comment]
I think the issue is that when converting widget to input, the context big node is trying to keep the type combo widget choices instead of consolidating down to the actual type.

![image](https://github.com/user-attachments/assets/63e4a8f9-7617-4c99-9b4e-9655de8bafac)

For example, here the sampler type is all the combo options, but it should actually be the string "COMBO", with the details of combo options in a separate field. This is the recommended way as combo options are not always stable. It might depends on what files are available in the local file system, and the list can be very long. Later we will introduce some meta combo types to lazy load corresponding combo options to alleviate this problem.

This issue should probably be moved to rgthree-comfy repo.
