### ISSUE TITLE
[Feature Request]: Node List for Drag-Popup too Shallow

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI_frontend#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The old context menu when pulling off an output would give a variable list (is a setting in ComfyUI) -- The new only presents the current filter box that has a large amount of wasted space, in addition to not being adjustable (size).

![image](https://github.com/user-attachments/assets/13045bde-d5b5-4076-a47b-75045f83964e)

Adjusting the CSS, or exposing settings to shrink this list are welcome. I do not think you need the separation now that you have removed descriptions.

![image](https://github.com/user-attachments/assets/af2affe5-959a-4e31-84e1-3e878ddb99a8)

### Proposed workflow

1. pull off output pin
2. get condensed, custom settings sized list panel
3. work faster.

**Comment by MNeMoNiCuZ** [comment]
Something like this, or mimicing the layout of Unreal Engine context menu would be quite preferrable.

![image](https://github.com/user-attachments/assets/289f774d-344b-4b3a-a634-bf8a368d6983)

Expandable categories, as well as sorting the results by categories would be good.


I'm not sure what the future plan is to keep things sorted by node packs vs. sorting by functionality.
If some kind of standard could be used instead of creating new categories to keep things together, things would be much easier to navigate.
