### ISSUE TITLE
[Feature Request]: Clicking on connection hilights connecion and connected nodes / ports

### ISSUE THREAD

**Issue by memo** [Comfy-Org/ComfyUI_frontend#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

In many node-based software, clicking (or even hoving) on a connection will hilight the connection and the ports on nodes it's connected to.
This makes debugging and following node graphs much easier. 
E.g.
Touchdesigner
Houdini
Max 

Max is a really good example of this. See attached video
(I've separated hilighting and rereouting into separate issues. See also #577)

https://github.com/user-attachments/assets/0ec9f99a-faf0-4d49-88e0-104f08609e76

**Comment by huchenlei** [comment]
There is already highlight on link when you click the connection slot, or select the node.

https://github.com/user-attachments/assets/b8e5a586-4443-456e-b05a-d7aff43fca29

I am not sure what is the proposal here. BTW, the litegraph side of suggestion should go to https://github.com/Comfy-Org/litegraph.js

**Comment by memoakten** [comment]
The suggestion is to hilight the connection and the ports it is connected to when you click on the connection. So that if you see a connection and you want to know where it's going to, you can trace it easily (because clicking on it will hilight it).
Clicking on the node it's coming from doesn't help in this case, because there might be loads of connections coming from a node and they are all hilighted.
