### ISSUE TITLE
[Feature Request]: Tool button to lock the whole canvas

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI_frontend#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A button in the toolbar that locks the whole canvas to avoid accidental modification. This can be useful for people who just want to run the workflow without modifying it.

### Proposed workflow

1. Click the lock button on the toolbar
2. The button icon becomes locked icon
3. Still being able to navigate the graph but cannot make modification to the graph

**Comment by alessandroperilli** [comment]
Correct. It basically does what the Freeze command does.

**Comment by alessandroperilli** [comment]
@huchenlei I saw the commit (and the subsequent change from lock/unlock to pan), but I think there's a misunderstanding. 

By locking the canvas, I didn't mean "stop the canvas from moving around". I meant "avoid accidental dragging of groups or nodes while, instead, you were trying just to drag the canvas". 

When a user tries to pan the workflow by clicking+holding+moving the mouse, if the mouse cursor is on a group header or on a node, instead of panning, these elements get moved. And if you accidentally move a group, you cause all sorts of problems. 

Of course, you can undo the action. Or you can pan with space+mouse movement. But dragging of the canvas is very common and hard to ditch as a habit. 

One or more custom node suites create a Freeze/Unfreeze contextual menu command that achieves what I am describing.

**Comment by huchenlei** [comment]
> @huchenlei I saw the commit (and the subsequent change from lock/unlock to pan), but I think there's a misunderstanding.
> 
> By locking the canvas, I didn't mean "stop the canvas from moving around". I meant "avoid accidental dragging of groups or nodes while, instead, you were trying just to drag the canvas".
> 
> When a user tries to pan the workflow by clicking+holding+moving the mouse, if the mouse cursor is on a group header or on a node, instead of panning, these elements get moved. And if you accidentally move a group, you cause all sorts of problems.
> 
> Of course, you can undo the action. Or you can pan with space+mouse movement. But dragging of the canvas is very common and hard to ditch as a habit.
> 
> One or more custom node suites create a Freeze/Unfreeze contextual menu command that achieves what I am describing.

If you hold space and drag a node, it now pans the canvas instead
