### ISSUE TITLE
[Bug]: Node opacity doesn't work with colored nodes

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#928]
### Frontend Version

1.2.62

### Expected Behavior

The new node opacity feature should also work with colored nodes.

### Actual Behavior

Only non-colored nodes become translucent.

### Steps to Reproduce

https://github.com/user-attachments/assets/8b8ed680-d441-4a0d-a768-128756df3a81

### Debug Logs

```powershell
no errors
```

### Browser Logs

no errors

### What browsers do you use to access the UI ?

Google Chrome

**Comment by christian-byrne** [comment]
I can add the other colors. It should be centralized with the code that lightens colors on light theme:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/4052fc55f331469607c5e5275a7423c8a6c4f419/src/scripts/app.ts#L1569-L1571

The colors should be adjusted by changing LiteGraph properties if possible. Otherwise, `lightenColor` and `applyOpacity` need to be memoized as they would be called every draw.
