### ISSUE TITLE
[Feature Request]: User selectable colors for bypassed and muted nodes

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI_frontend#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have a lot of bypassed nodes on my workflows, and I find all the pink colors too distracting.

I would like to use a dark color ( similar to the muted nodes ).

But the best way to deal with this is probably to let the user select the color for each use case, since everyone has its own preferences.

---

If this is too complex, just and an option to switch the current colors:

- dark = bypassed
- pink = muted

### Proposed workflow

.

**Comment by mcmonkey4eva** [comment]
The correct way to do this is probably via the _Themes system_ that lets you customize colors in general, which internally maps to the _`ColorPalette.ts`_ classes, however it's currently not designed in a way that's particular amenable to being extended and used fully.

Notably bypass/mute is implemented inside `app.ts`, and `ColorPalette.ts` requires `app.ts` to be ready at import time, ie `app.ts` cannot import `ColorPalette.ts` to actually read color data from it (ow). This happens because ColorPalette is treated as an extension, not a core component, meaning it uses `app.registerExtension` inside itself.

Also it's organized into 'comfy base' and 'litegraph base', neither of which are correct for "new color" (albeit either can happily used despite technical incorrectness, or just make a new category)

So some reorganization of this code is needed before it can be used to fully allow free customization of colors.
Or, we could define the colors as just random variables somewhere, and let the extension update them, which is in line with how the current code for it is implemented, but is very much a hack.

**Comment by mcmonkey4eva** [comment]
PR for the hacky version https://github.com/Comfy-Org/ComfyUI_frontend/pull/993

Green bypass to demonstrate
![371061017-09416755-e0fc-4205-b5b9-fd304a4eff17](https://github.com/user-attachments/assets/8309e309-46c2-43bd-8e1a-accc64fe458c)

Only did bypass atm - currently muted notes just go transparent and don't alter color, so allowing coloring them would need to be done separately

**Comment by JorgeR81** [comment]
If you're planning a more robust implementation for this: 

Why not make bypassed / muted states independent from color ?
Maybe just add some transparency and icons for bypassed / muted states, similar to the pin icon ( https://github.com/Comfy-Org/ComfyUI_frontend/issues/4763 )

Then the user could also select to have no color at all for these states.
